# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2dbe519e1516fc4ae8fc5ce83ea40eaf27052a19b2d8795095aa08de320fb63b3811c02183927568df838cbeeb5e0662be4226b5dd05b70fa8525c5e6d5bc3cf

test:
  secret_key_base: 103b36508f0cc84541feed175640c7d65e6d56f01a3b7f60f6ba88ecc35a485dcc54b561f90158c3cb2c1233e836874d1b497e773004fd5efa41dd13981a99f2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
